### ISSUE TITLE
Improve Develompent Process

### ISSUE THREAD

**Issue by StefanSchade** [StefanSchade/Java-AdventureGame#35]
**Improve Develompent Process**

- [ ] **issue #14** unit testing
- [ ] **issue #15** test branch
- [ ] **issue #16** circle ci test
